before:
  hooks:
    # this file would invalidate go source caches
    - sh -c "rm openapi/statik/statik.go || true"
    - docker build -f build/grpc/Dockerfile -t zitadel-base:local .
    - docker build -f build/zitadel/Dockerfile . -t zitadel-go-test --target go-codecov -o .artifacts/codecov
    - docker build -f build/zitadel/Dockerfile . -t zitadel-go-base --target go-copy -o .artifacts/grpc/go-client
    - sh -c "cp -r .artifacts/grpc/go-client/* ."
    - docker build -f build/console/Dockerfile . -t zitadel-npm-base --target npm-copy -o .artifacts/grpc/js-client
    - docker build -f build/console/Dockerfile . -t zitadel-npm-console --target angular-export -o .artifacts/console
    - sh -c "cp -r .artifacts/console/* internal/api/ui/console/static/"

builds:
  - env:
      - CGO_ENABLED=0
    binary: zitadel-debug
    gcflags: all=-N -l
    ldflags: ""

dist: .artifacts/goreleaser

gomod:
  proxy: false
